apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: kubekite
  namespace: buildkite
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "watch", "list"]
- apiGroups: ["batch", "extensions"]
  resources: ["jobs"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: kubekite
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: kubekite
  namespace: buildkite
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: kubekite
subjects:
- kind: ServiceAccount
  name: kubekite
  namespace: buildkite
